const character = "just typescript";

console.log(character);

// to compile write "tsc app.ts" or "tsc app.ts appjs" on the terminal after installing typescript and more...
// if we do not write app.js like above, it will automatically create js file and translate i our typescript codes into javascript ...
